### ISSUE TITLE
RWD排版問題

### ISSUE THREAD

**Issue by ericbig66** [ericbig66/personalinfo.github.io#1]
正常大小(解析度1920*1080  DPI:125%)
![image](https://user-images.githubusercontent.com/47971342/57475849-ccb54180-72c7-11e9-991f-341d203cb05a.png)

將視窗變窄==>出現文字被強迫切除的問題
![image](https://user-images.githubusercontent.com/47971342/57476041-582ed280-72c8-11e9-91f9-f80d55fbadcb.png)

**Comment by qwe987299** [comment]
幻燈片內最外層(#club_content)設定成「100% x 數量(3)」寬
幻燈片內的內層(.artical)設定成「calc(100%/3)」寬，運用 box-sizing: border-box; 就可以不用扣 padding 的部分寬度
接下來就是你 JS 要改 (每次向左-100%)
這樣可完全解決問題
※ 關於寬度 CSS 真的建議用 % 盡量不要用 px 鎖死寬度

**Comment by ericbig66** [comment]
謝謝你，我的問題已經解決了
